# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MObject": "00_core_is.ipynb",
         "MObjectContinuous": "00_core.ipynb",
         "MObjectDiscrete": "00_core.ipynb",
         "MObjectConnected": "00_core.ipynb",
         "MModel": "00_core_is.ipynb",
         "MAObject": "00_core_rs_ref.ipynb",
         "MProperty": "00_core_is.ipynb",
         "MMethod": "00_core_is.ipynb",
         "MRelation": "00_core_is.ipynb",
         "MThings": "00_core_rs_ref.ipynb",
         "MAThing": "00_core_rs_ref.ipynb"}

modules = ["rs/core.py",
           "is/core.py",
           "rs/ref.py"]

doc_url = "https://fastai.github.io/arc2020/"

git_url = "https://github.com/fastai/arc2020/tree/master/"

def custom_doc_links(name): return None
