# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MObject": "00_core.ipynb",
         "MObjectContinuous": "00_core.ipynb",
         "MObjectDiscrete": "00_core.ipynb",
         "MObjectConnected": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/arc2020/"

git_url = "https://github.com/fastai/arc2020/tree/master/"

def custom_doc_links(name): return None
