# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['MObject', 'MObjectContinuous', 'MObjectDiscrete', 'MObjectConnected']

# Cell
class MObject:
    """A base class"""
    def hello():
        print("Hello!")

# Cell
#@docs
class MObjectContinuous(MObject):
    """A Continuous Object"""
    def __init__(self):
        self.data = []
    def helloCont(self):
        print("HelloCont!")

class MObjectDiscrete(MObject):
    """A Continuous Object"""
    def __init__(self):
        self.data = []
    def helloCont(self):
        print("HelloCont!")

class MObjectConnected(MObject):
    """A Continuous Object"""
    def __init__(self):
        self.data = []
    def helloCont(self):
        print("HelloCont!")