# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core_rs_ref.ipynb (unless otherwise specified).

__all__ = ['MThings', 'MAObject', 'MAThing']

# Cell
class MThings(MAObject):
    """A base property"""
    def __init__(self):
        self.data = []

class MAObject():
    """A base Abstract Object"""
    def __init__(self):
        self.data = []
    """A base property"""
    def hello():
        print("Hello!")

class MAThing(MAObject):
    """A base Abstract Object"""
    def __init__(self):
        self.data = []
    """A base property"""
    def hello():
        print("Hello!")