# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core_is.ipynb (unless otherwise specified).

__all__ = ['MModel', 'MAObject', 'MObject', 'MProperty', 'MMethod', 'MRelation']

# Cell

class MModel():
    """A base property"""
    def __init__(self):
        self.data = []

class MAObject():
    """A base Abstract Object"""
    def __init__(self):
        self.data = []
    """A base property"""
    def hello():
        print("Hello!")

class MObject(MAObject):
    """A base Object"""
    def __init__(self):
        self.data = []
    def hello():
        print("Hello!")

class MProperty(MAObject):
    """A base Property"""
    def __init__(self):
        self.data = []
    def hello():
        print("Hello!")

class MMethod(MAObject):
    """A base Method"""
    def __init__(self):
        self.data = []
    def hello():
        print("Hello!")

class MRelation(MAObject):
    """A base Relation"""
    def __init__(self):
        self.data = []
    def hello():
        print("Hello!")